version: '3.8'

services:
  database:
    image: postgres:17-trixie
    environment:
      POSTGRES_DB: timeline
      POSTGRES_USER: timeline_user
      POSTGRES_PASSWORD: timeline_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - timeline_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://timeline_user:timeline_password@database:5432/timeline
      RUST_LOG: info
      # CORS Domain Configuration
      # Set to "localhost" for local development/testing
      # Set to your production domain (e.g., "timeline.example.com") for production
      CORS_DOMAIN: localhost
      # TLS Enforcement (when behind reverse proxy)
      # Set to "true" to require TLS connections (checks X-Forwarded-Proto header)
      # Set to "false" to allow HTTP (default for local development)
      REQUIRE_TLS: "false"
    depends_on:
      - database
    networks:
      - timeline_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  timeline_network:
    driver: bridge